baseURL = 'https://parisjug.hardcoding.fr/'
defaultContentLanguage = 'fr'
languageCode = 'fr-fr'
title = 'Paris Java User Group'
theme = 'mainroad'
googleAnalytics = "UA-62610761-1"

[Params]
  description = "Bienvenue au Paris Java User Group !" # Site description. Used in meta description
  copyright = "Paris JUG" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  images = ["img/featured.png"]
  readmore = true # Show "Read more" button in list if true
  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  mainSections = ["events"] # Specify section pages to show on home page and the "Recent articles" widget
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/medium-zoom.min.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/logo.png" # Logo image. Path relative to "static"
  title = "Paris JUG" # Logo title, otherwise will use site title
  subtitle = "Bienvenue au Paris Java User Group !" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["mailinglist", "sponsors", "social", "taglist"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "parisjug"
#  linkedin = "username"
  github = "parisjug"
#  email = "example@example.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://www.youtube.com/channel/UCPNEu33xtYpKjQKcn9E5m0Q"
  icon = "svg/youtube.svg" # Optional. Path relative to "layouts/partials"

[caches]
  [caches.getcsv]
    dir = ':resourceDir/_gen'
  [caches.getjson]
    dir = ':resourceDir/_gen'
  [caches.getresource]
    dir = ':resourceDir/_gen'

[social]
  twitter = 'parisjug'
